### ISSUE TITLE
Why the use of a WeakMap for the child nodes?

### ISSUE THREAD

**Issue by glromeo** [WebReflection/document-persistent-fragment#3]
I am just curious to know why you made this design decision.
Thank you for your work by the way it's a trove and great source of inspiration for me!

**Comment by WebReflection** [comment]
I am not sure I am following ... the only *WeakMap* used is for the the *DPF* list of child nodes ... that couples such list with the persistent fragment itself, it never makes related nodes GCable, quite the opposite, it retains all of them that are part of it until the fragment itself is collected. What am I missing? 🤔

**Comment by glromeo** [comment]
My mistake... I was wrapping my head around why the weakmap instead of just the array as a field and the subject was my misinterpretation 😅

**Comment by WebReflection** [comment]
that choice comes from times where private class fields were non-existent ... today I'd use a private field but, behind the scene, private fields are basically weakmaps anyway ... or at least that's how these get translated by transpilers so ... this proposal is here to stay as reference for the day somebody at *WHATWG* would re-consider it ... it's not really maintained, I won't work on this, it's for logic, idea, and presentation purpose that this repo exists, nothing else (but one could use it ... as I do without patching the world in my DOM related libraries, where every fragment basically represents this very same concept of not disappearing from the list of nodes that get diffed per every reactive update).
